harps: harps::DynamicMonophony Class Reference
harps::DynamicMonophony Class Reference
#include <instrument.hpp>
Public Member Functions
DynamicMonophony ()
virtual ~DynamicMonophony ()
template<typename SampleType>
void operator() (Buffer< SampleType > &_buffer)
int noteOn (int _note, float _touch)
void noteOff (int _dummy=0)
void noteWait (int _dummy=0)
void setPitchBend (float _pitch)
void reset ()
Note::NoteState getStatus () const
double getGlobalTime ()
void programChange (const char *_filename)
Detailed Description
モジュールの発音とクロックを管理するインスツルメントクラスです。 ダイナミックモノフォニーは外部トーンモジュールを読み込んで同時に1音を鳴らすことが出来ます。
Constructor & Destructor Documentation
harps::DynamicMonophony::DynamicMonophony () [inline]
コンストラクタ
virtual harps::DynamicMonophony::~DynamicMonophony () [inline, virtual]
デストラクタ
Member Function Documentation
template<typename SampleType> void harps::DynamicMonophony::operator() (Buffer< SampleType > & _buffer) [inline]
モジュールを実行し、クロックを1ブロック分進めます。
Parameters:
_buffer 実行結果を出力するバッファブロック
int harps::DynamicMonophony::noteOn (int _note, float _touch) [inline]
指定した鍵盤を押された状態にします。
Parameters:
_note 鍵盤(MIDIノートナンバーで指定)
_touch 鍵盤を押す強さ
Returns:
ノートID(モノフォニーは1音しか発音しないため、ノートIDは必ず0になります)
References harps::Note::noteOn(), and harps::CurrentTime::noteOn().
void harps::DynamicMonophony::noteOff (int _dummy = 0) [inline]
現在押している鍵盤から指を離します。モジュールによっては鍵盤から指を離してもすぐに音は止まりません。音を完全に止めてインスツルメントを待機状態にするにはnoteWaitを呼び出す必要があります。
Parameters:
_dummy ノートID(ポリフォニーとインターフェースを揃えるために用意されています。この値は無視されます)
References harps::Note::noteOff(), and harps::CurrentTime::noteOff().
void harps::DynamicMonophony::noteWait (int _dummy = 0) [inline]
発音処理を終了します。
Parameters:
_dummy ノートID(ポリフォニーとインターフェースを揃えるために用意されています。この値は無視されます)
References harps::Note::noteWait().
void harps::DynamicMonophony::setPitchBend (float _pitch) [inline]
ピッチベンドします。設定したピッチベンド値はresetされるまで引き継がれます。
Parameters:
_pitch ピッチ(1.0で音階が1上がり、12.0で1オクターブ上がります)
References harps::CurrentTime::setPitchBend().
void harps::DynamicMonophony::reset () [inline]
インスツルメントをリセットします。設定されたピッチベンドは0に戻ります。
References harps::CurrentTime::reset().
Note::NoteState harps::DynamicMonophony::getStatus () const [inline]
現在のノートの状態を取得します。
Returns:
ノートの状態
References harps::Note::getStatus().
double harps::DynamicMonophony::getGlobalTime () [inline]
現在の処理中の箇所の時刻を返します。
Returns:
現在時刻
References harps::CurrentTime::getTime().
void harps::DynamicMonophony::programChange (const char * _filename) [inline]
モジュールを変更します。
Parameters:
_filename 新しいモジュールのファイル名
The documentation for this class was generated from the following file:
rc/harps/include/harps/instrument.hpp