harps: harps::input::Tracks< OutputType, ReaderType, BufferType, track_count > Class Template Reference
harps::input::Tracks< OutputType, ReaderType, BufferType, track_count > Class Template Reference
#include <simple.hpp>
Public Member Functions
Tracks (const char *_sink)
void setScore (unsigned int _target, const char *_prog, const harps::input::Score *_score)
void operator() ()
bool isEnd ()
Classes
class TrackRunner
Detailed Description
template<typename OutputType, typename ReaderType, typename BufferType, unsigned int track_count>
class harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >
複数のSimpleReaderを束ねて2つ以上の楽器を同時に演奏します。
Constructor & Destructor Documentation
template<typename OutputType, typename ReaderType, typename BufferType, unsigned int track_count> harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >::Tracks (const char * _sink) [inline]
コンストラクタ
Parameters:
_sink オーディオデータの出力先
Member Function Documentation
template<typename OutputType, typename ReaderType, typename BufferType, unsigned int track_count> void harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >::operator() () [inline]
楽譜を読んでオーディオデータを生成し、指定された出力先に出力します。
References harps::Buffer< _SampleType >::get(), harps::Normalizer< tail >::getAmp(), harps::reduceNormalizingNoize(), and harps::Normalizer< tail >::setValue().
template<typename OutputType, typename ReaderType, typename BufferType, unsigned int track_count> bool harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >::isEnd () [inline]
楽譜が終端に達しているかどうかを調べます
Returns:
終端ならtrue そうでなければfalse
The documentation for this class was generated from the following file:
rc/harps/include/harps/input/simple.hpp