harps: harps::Buffer< _SampleType > Class Template Reference
harps::Buffer< _SampleType > Class Template Reference
#include <buffer.hpp>
Public Types
typedef _SampleType SampleType
Public Member Functions
Buffer ()
virtual ~Buffer ()
SampleType * get ()
SampleType * getLeft ()
SampleType * getRight ()
const SampleType * get () const
const SampleType * getLeft () const
const SampleType * getRight () const
void setStereo ()
void setMonoral ()
bool isStereo () const
void requestContinue ()
void requestEnd ()
void reset ()
bool shouldEnd ()
void mergeVote (const Buffer< _SampleType > &_source)
unsigned int getContinueRequestCount () const
unsigned int getEndRequestCount () const
void setUsed ()
bool getUsed () const
Detailed Description
template<typename _SampleType>
class harps::Buffer< _SampleType >
モジュールの出力を保持するバッファです。 モノラル、またはステレオであらかじめ指定された長さの音を保持します。
Constructor & Destructor Documentation
template<typename _SampleType> harps::Buffer< _SampleType >::Buffer () [inline]
コンストラクタ
template<typename _SampleType> virtual harps::Buffer< _SampleType >::~Buffer () [inline, virtual]
デストラクタ
Member Function Documentation
template<typename _SampleType> SampleType* harps::Buffer< _SampleType >::get () [inline]
モノラルバッファに使われている配列を取得します。
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::operator()(), harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >::operator()(), and harps::reduceNormalizingNoize().
template<typename _SampleType> SampleType* harps::Buffer< _SampleType >::getLeft () [inline]
ステレオバッファに使われている左側の音を保持している配列を取得します。
Returns:
配列
Referenced by harps::output::ALSA< is_stereo, bytes_per_sample >::operator()(), and harps::output::Wave< is_stereo, bytes_per_sample >::operator()().
template<typename _SampleType> SampleType* harps::Buffer< _SampleType >::getRight () [inline]
ステレオバッファに使われている右側の音を保持している配列を取得します。
Returns:
配列
Referenced by harps::output::ALSA< is_stereo, bytes_per_sample >::operator()(), and harps::output::Wave< is_stereo, bytes_per_sample >::operator()().
template<typename _SampleType> const SampleType* harps::Buffer< _SampleType >::get () const [inline]
モノラルバッファに使われている配列を取得します。
Returns:
配列
template<typename _SampleType> const SampleType* harps::Buffer< _SampleType >::getLeft () const [inline]
ステレオバッファに使われている左側の音を保持している配列を取得します。
Returns:
配列
template<typename _SampleType> const SampleType* harps::Buffer< _SampleType >::getRight () const [inline]
ステレオバッファに使われている右側の音を保持している配列を取得します。
Returns:
配列
template<typename _SampleType> void harps::Buffer< _SampleType >::setStereo () [inline]
バッファをステレオにします。
template<typename _SampleType> void harps::Buffer< _SampleType >::setMonoral () [inline]
バッファをモノラルにします。
template<typename _SampleType> bool harps::Buffer< _SampleType >::isStereo () const [inline]
バッファがステレオかどうか確認します。
Returns:
ステレオの場合true モノラルの場合false
template<typename _SampleType> void harps::Buffer< _SampleType >::requestContinue () [inline]
継続要求を出します。このバッファで音が終わってもらっては困る場合に、モジュールが呼び出します。 継続要求が全く無く、終了要求が1回以上ある場合バッファは音の終了をインスツルメントに提案します。 実際に音が終了するかどうかはインスツルメントに依存します。
template<typename _SampleType> void harps::Buffer< _SampleType >::requestEnd () [inline]
終了要求を出します。このバッファで音が終わっていると考えられる場合に、モジュールが呼び出します。 継続要求が全く無く、終了要求が1回以上ある場合バッファは音の終了をインスツルメントに提案します。 実際に音が終了するかどうかはインスツルメントに依存します。
template<typename _SampleType> void harps::Buffer< _SampleType >::reset () [inline]
バッファの状態をリセットします。リセットされるのは状態だけでバッファの値はクリアされません。
template<typename _SampleType> bool harps::Buffer< _SampleType >::shouldEnd () [inline]
音を終了すべきかどうかを判断します。 継続要求が全く無く、終了要求が1回以上ある場合バッファは音の終了をインスツルメントに提案します。 実際に音が終了するかどうかはインスツルメントに依存します。
Returns:
終了すべきならtrue 継続すべきならfalse
template<typename _SampleType> void harps::Buffer< _SampleType >::mergeVote (const Buffer< _SampleType > & _source) [inline]
複数のバッファの投票を足し合わせます。
Parameters:
_source 足し合わせるバッファ
template<typename _SampleType> unsigned int harps::Buffer< _SampleType >::getContinueRequestCount () const [inline]
継続要求の回数を取得します。
Returns:
回数
template<typename _SampleType> unsigned int harps::Buffer< _SampleType >::getEndRequestCount () const [inline]
終了要求の回数を取得します。
Returns:
回数
template<typename _SampleType> void harps::Buffer< _SampleType >::setUsed () [inline]
バッファに使用済フラグを立てます。
template<typename _SampleType> bool harps::Buffer< _SampleType >::getUsed () const [inline]
バッファが使用済かどうか調べます。
Returns:
使用済ならtrue 未使用ならfalse
The documentation for this class was generated from the following file:
rc/harps/include/harps/buffer.hpp