harps: harps::Note Class Reference
harps::Note Class Reference
#include <note.hpp>
Public Types
enum NoteState { NOTE_ON = 1, NOTE_OFF = 2, NOTE_WAIT = 3 }
Public Member Functions
Note ()
virtual ~Note ()
void noteOn (float _touch=1.0f)
void noteOff ()
void noteWait ()
NoteState getStatus () const
float getTouch () const
Detailed Description
ノートは発音中の音の音階と鍵盤を押した強さ、鍵盤の現在の状態を保持します。
Constructor & Destructor Documentation
harps::Note::Note () [inline]
コンストラクタ
virtual harps::Note::~Note () [inline, virtual]
デストラクタ
Member Function Documentation
void harps::Note::noteOn (float _touch = 1.0f) [inline]
指定した強さで鍵盤を押します。
Parameters:
_touch 鍵盤を押す強さ
Referenced by harps::DynamicMonophony::noteOn().
void harps::Note::noteOff () [inline]
鍵盤から指を離します
Referenced by harps::DynamicMonophony::noteOff().
void harps::Note::noteWait () [inline]
発音を終了します
Referenced by harps::DynamicMonophony::noteWait().
NoteState harps::Note::getStatus () const [inline]
現在の音の状態を取得します
Returns:
音の状態
Referenced by harps::DynamicMonophony::getStatus().
float harps::Note::getTouch () const [inline]
現在発音中の音の鍵盤が押された時の強さを取得します
Returns:
鍵盤を押した強さ
The documentation for this class was generated from the following file:
rc/harps/include/harps/note.hpp