harps: harps::CurrentTime Class Reference
harps::CurrentTime Class Reference
#include <clock.hpp>
Public Types
enum { MATRIX_COUNT = 3 }
Public Member Functions
CurrentTime (Time _tick_length)
virtual ~CurrentTime ()
template<unsigned int _which>
double getTime (unsigned int _offset) const
void reset ()
template<unsigned int _which>
void swapMatrix (TimeMatrix &_matrix)
template<unsigned int _which>
const TimeMatrix & getMatrix () const
void noteOn (int _note)
void noteOff ()
void setPitchBend (float _pitch)
float getToneFrequency () const
int getTone () const
float getPitchBend () const
void tick (unsigned int _sample_count)
Detailed Description
現在時刻を保持します。現在時刻は4つの時刻変換行列を通して取得することができます。
Constructor & Destructor Documentation
harps::CurrentTime::CurrentTime (Time _tick_length) [inline]
コンストラクタ
Parameters:
_tick_lenght 1クロックの時間
virtual harps::CurrentTime::~CurrentTime () [inline, virtual]
デストラクタ
Member Function Documentation
template<unsigned int _which> double harps::CurrentTime::getTime (unsigned int _offset) const [inline]
現在時刻から_offsetクロック先の時刻を指定した行列を通して取得します。
Parameters:
_offset 現在時刻からのずれ
Returns:
指定された条件での時刻
Referenced by harps::DynamicMonophony::getGlobalTime().
void harps::CurrentTime::reset () [inline]
時刻をリセットします。
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::reset(), and harps::DynamicMonophony::reset().
template<unsigned int _which> void harps::CurrentTime::swapMatrix (TimeMatrix & _matrix) [inline]
時刻変換行列を交換します。引数で渡された行列に古い行列が代入されます。
Parameters:
_matrix 新しい行列
template<unsigned int _which> const TimeMatrix& harps::CurrentTime::getMatrix () const [inline]
時刻変換行列を取得します。
Returns:
時刻変換行列
void harps::CurrentTime::noteOn (int _note) [inline]
鍵盤が押されたことを通知します。ノートナンバーからトーンクロックの時刻変換行列が自動的に生成されます。また、ローカルクロックとキークロックが0をさすようになります。
Parameters:
_note ノートナンバー
References harps::noteToFrequency().
Referenced by harps::DynamicMonophony::noteOn().
void harps::CurrentTime::noteOff () [inline]
鍵盤が離されたことを通知します。また、キークロックが0をさすようになります。
Parameters:
_note ノートナンバー
Referenced by harps::DynamicMonophony::noteOff().
void harps::CurrentTime::setPitchBend (float _pitch) [inline]
ピッチベンドします。
Parameters:
_pitch ピッチベンド値
References harps::loop(), and harps::noteToFrequency().
Referenced by harps::DynamicMonophony::setPitchBend().
float harps::CurrentTime::getToneFrequency () const [inline]
現在の音の周波数を取得します。
Returns:
周波数
int harps::CurrentTime::getTone () const [inline]
現在の音の音階を取得します。
Returns:
ノートナンバー
float harps::CurrentTime::getPitchBend () const [inline]
現在のピッチベンド値を取得します。
Returns:
ピッチベンド値
void harps::CurrentTime::tick (unsigned int _sample_count) [inline]
時刻を指定したクロック数分進めます。
Parameters:
_sample_count クロック数
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::operator()().
The documentation for this class was generated from the following file:
rc/harps/include/harps/clock.hpp