harps: harps::Normalizer< tail > Class Template Reference
harps::Normalizer< tail > Class Template Reference
#include <normalize.hpp>
Public Member Functions
Normalizer ()
virtual ~Normalizer ()
void setValue (float _arg_value)
float getAmp ()
Detailed Description
template<int tail>
class harps::Normalizer< tail >
ノーマライザは波形が出力可能な振幅を越えてしまう場合にどのくらい音量を絞れば良いかを計算します。
Constructor & Destructor Documentation
template<int tail> harps::Normalizer< tail >::Normalizer () [inline]
コンストラクタ
template<int tail> virtual harps::Normalizer< tail >::~Normalizer () [inline, virtual]
デストラクタ
Member Function Documentation
template<int tail> void harps::Normalizer< tail >::setValue (float _arg_value) [inline]
波形データを供給します
Parameters:
_arg_value サンプル値
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::operator()(), and harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >::operator()().
template<int tail> float harps::Normalizer< tail >::getAmp () [inline]
適切な音量を取得します
Returns:
スケール値
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::operator()(), and harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >::operator()().
The documentation for this class was generated from the following file:
rc/harps/include/harps/normalize.hpp