harps: harps::DynamicPolyphony< MonophonyType, max_polyphony > Class Template Reference
harps::DynamicPolyphony< MonophonyType, max_polyphony > Class Template Reference
#include <instrument.hpp>
Public Member Functions
DynamicPolyphony ()
virtual ~DynamicPolyphony ()
template<typename SampleType>
void operator() (Buffer< SampleType > &_buffer)
int noteOn (int _note, float _touch)
void noteOff (int _note_id)
void setPitchBend (int _note_id, float _pitch)
void setPitchBend (float _pitch)
void reset ()
int findMonophony (int _note_id)
double getGlobalTime ()
void programChange (const char *_filename)
Classes
class Renderer
Detailed Description
template<typename MonophonyType, unsigned int max_polyphony>
class harps::DynamicPolyphony< MonophonyType, max_polyphony >
モジュールの発音とクロックを管理するインスツルメントクラスです。 ダイナミックポリフォニーは外部トーンモジュールを読み込んで同時に複数音を鳴らすことが出来ます。
Constructor & Destructor Documentation
template<typename MonophonyType, unsigned int max_polyphony> harps::DynamicPolyphony< MonophonyType, max_polyphony >::DynamicPolyphony () [inline]
コンストラクタ
template<typename MonophonyType, unsigned int max_polyphony> virtual harps::DynamicPolyphony< MonophonyType, max_polyphony >::~DynamicPolyphony () [inline, virtual]
デストラクタ
Member Function Documentation
template<typename MonophonyType, unsigned int max_polyphony> template<typename SampleType> void harps::DynamicPolyphony< MonophonyType, max_polyphony >::operator() (Buffer< SampleType > & _buffer) [inline]
全てのモジュールを実行しクロックを1ブロック分進めます。
Parameters:
_buffer 実行結果の総和を出力するバッファブロック
References harps::Buffer< _SampleType >::get(), harps::Normalizer< tail >::getAmp(), harps::reduceNormalizingNoize(), harps::Normalizer< tail >::setValue(), and harps::CurrentTime::tick().
template<typename MonophonyType, unsigned int max_polyphony> int harps::DynamicPolyphony< MonophonyType, max_polyphony >::noteOn (int _note, float _touch) [inline]
指定した鍵盤を押された状態にします。
Parameters:
_note 鍵盤(MIDIノートナンバーで指定)
_touch 鍵盤を押す強さ
Returns:
ノートID
template<typename MonophonyType, unsigned int max_polyphony> void harps::DynamicPolyphony< MonophonyType, max_polyphony >::noteOff (int _note_id) [inline]
現在押している鍵盤から指を離します。モジュールによっては鍵盤から指を離してもすぐに音は止まりません。音を完全に止めてインスツルメントを待機状態にするにはnoteWaitを呼び出す必要があります。
Parameters:
_note_id 指を離す鍵盤をnoteOn時に取得したノートIDで指定します
References harps::DynamicPolyphony< MonophonyType, max_polyphony >::findMonophony().
template<typename MonophonyType, unsigned int max_polyphony> void harps::DynamicPolyphony< MonophonyType, max_polyphony >::setPitchBend (int _note_id, float _pitch) [inline]
ピッチベンドします。設定したピッチベンド値は指定した音のみに影響します。
Parameters:
_note_id ノートID
_pitch ピッチ(1.0で音階が1上がり、12.0で1オクターブ上がります)
References harps::DynamicPolyphony< MonophonyType, max_polyphony >::findMonophony().
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::setPitchBend().
template<typename MonophonyType, unsigned int max_polyphony> void harps::DynamicPolyphony< MonophonyType, max_polyphony >::setPitchBend (float _pitch) [inline]
ピッチベンドします。設定したピッチベンド値は発音中の全ての音に影響します。
Parameters:
_pitch ピッチ(1.0で音階が1上がり、12.0で1オクターブ上がります)
References harps::DynamicPolyphony< MonophonyType, max_polyphony >::setPitchBend().
template<typename MonophonyType, unsigned int max_polyphony> void harps::DynamicPolyphony< MonophonyType, max_polyphony >::reset () [inline]
インスツルメントをリセットします。それまでに生成されたNoteIDは全て無効になります。無効になったNoteIDを使ってnoteOffした場合の動作は未定義です。
References harps::CurrentTime::reset().
template<typename MonophonyType, unsigned int max_polyphony> int harps::DynamicPolyphony< MonophonyType, max_polyphony >::findMonophony (int _note_id) [inline]
指定したIDの音が割り当てられているモノフォニーインスツルメントのIDを返します。これはnoteOnした音が実際に発音されているか、あるいはインスツルメントが最大同時発音数に達した等の理由によって発音されなかったかを調べるために使うことが出来ます。
Parameters:
_note_id ノートID
Returns:
モノフォニーインスツルメントのID(見つからなかった場合は-1)
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::noteOff(), and harps::DynamicPolyphony< MonophonyType, max_polyphony >::setPitchBend().
template<typename MonophonyType, unsigned int max_polyphony> double harps::DynamicPolyphony< MonophonyType, max_polyphony >::getGlobalTime () [inline]
現在の処理中の箇所の時刻を返します。
Returns:
現在時刻
template<typename MonophonyType, unsigned int max_polyphony> void harps::DynamicPolyphony< MonophonyType, max_polyphony >::programChange (const char * _filename) [inline]
モジュールを変更します。
Parameters:
_filename 新しいモジュールのファイル名
The documentation for this class was generated from the following file:
rc/harps/include/harps/instrument.hpp