harps: harps Namespace Reference
harps Namespace Reference
Classes
class Buffer
class ClockMatrixCalc
class ClockMatrixCalc< LOCAL >
class ClockMatrixCalc< KEY >
class ClockMatrixCalc< TONE >
class CurrentTime
class Clock
class DynamicModuleSocket
class DynamicModuleSlot
class Dummy
class HarpsException
class ModuleNotFound
class UnableToCreateInstance
class UnableToOpenSink
class SinkConfigurationFailed
class SinkOutputFailed
class DynamicMonophony
class DynamicPolyphony
class Normalizer
class Note
class SharedBuffer
Namespaces
namespace compornent
namespace input
namespace output
Typedefs
typedef double Time
typedef std::pair< Time, Time > TimeMatrix
Enumerations
enum { GLOBAL = -1, LOCAL = 0, KEY = 1, TONE = 2 }
Functions
float noteToFrequency (float _note)
const char * getModulePath ()
template<typename SampleType>
void reduceNormalizingNoize (Buffer< SampleType > &_buffer)
double getTime ()
void sleep (double _until)
float loop (float _source)
double loop (double _source)
float sin (float _theta)
double sin (double _theta)
float volume (float _linear)
double volume (double _linear)
float triangle (float _theta)
double triangle (double _theta)
float rectangle (float _duty, float _theta)
double rectangle (double _duty, double _theta)
float nes (float _theta)
double nes (double _theta)
Detailed Description
harpsはテンプレートベースで作られたモジュールシンセサイザーです。 harpsではスタック操作の最適化の効果を最大限に得るために殆どの関数はインラインかされています。
Function Documentation
const char * harps::getModulePath ()
モジュールを探すパスを取得します。モジュールを探すパスはビルド時に指定されたprefixをもとに決定されます。
Returns:
探索パス
Referenced by harps::DynamicModuleSlot::DynamicModuleSlot().
double harps::getTime () [inline]
現在時刻を取得します。
Returns:
現在時刻
Referenced by sleep().
double harps::loop (double _source) [inline]
入力値を0.0から1.0(1.0を含まない)の間でループします。
Parameters:
_source 入力値
Returns:
出力値
float harps::loop (float _source) [inline]
入力値を0.0から1.0(1.0を含まない)の間でループします。
Parameters:
_source 入力値
Returns:
出力値
Referenced by nes(), rectangle(), harps::CurrentTime::setPitchBend(), sin(), and triangle().
double harps::nes (double _theta) [inline]
ファミコンっぽい三角波を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
triangle(_theta)をある程度の精度で丸めたもの
References loop().
float harps::nes (float _theta) [inline]
ファミコンっぽい三角波を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
triangle(_theta)をある程度の精度で丸めたもの
References loop().
float harps::noteToFrequency (float _note) [inline]
MIDIノートナンバーから周波数に変換します。
Parameters:
_note ノートナンバー
Returns:
周波数
Referenced by harps::CurrentTime::noteOn(), and harps::CurrentTime::setPitchBend().
double harps::rectangle (double _duty, double _theta) [inline]
矩形波を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
rectangle(_theta)
References loop().
float harps::rectangle (float _duty, float _theta) [inline]
矩形波を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
rectangle(_theta)
References loop().
template<typename SampleType> void harps::reduceNormalizingNoize (Buffer< SampleType > & _buffer) [inline]
正規化のスケール値にローパスフィルタをかけて急激なスケーリングによるノイズを低減します。
Parameters:
_buffer スケール値バッファ
References harps::Buffer< _SampleType >::get().
Referenced by harps::DynamicPolyphony< MonophonyType, max_polyphony >::operator()(), and harps::input::Tracks< OutputType, ReaderType, BufferType, track_count >::operator()().
double harps::sin (double _theta) [inline]
テーブルを使って高速に正弦の近似値を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
sin(_theta)
References loop().
float harps::sin (float _theta) [inline]
テーブルを使って高速に正弦の近似値を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
sin(_theta)
References loop().
void harps::sleep (double _until) [inline]
指定した時刻までプロセスを停止させます。
Parameters:
_until 再開予定時刻
References getTime().
double harps::triangle (double _theta) [inline]
三角波を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
triangle(_theta)
References loop().
float harps::triangle (float _theta) [inline]
三角波を返します。
Parameters:
_theta 角度(1周を1.0とする)
Returns:
triangle(_theta)
References loop().
double harps::volume (double _linear) [inline]
テーブルを使って高速に音量と実際の振幅の変換を行います。
Parameters:
_linear 音量
Returns:
振幅
float harps::volume (float _linear) [inline]
テーブルを使って高速に音量と実際の振幅の変換を行います。
Parameters:
_linear 音量
Returns:
振幅